package com.example.independencework.domain;

import com.example.independencework.R;

import java.util.ArrayList;

public class DataTopics {

    public static ArrayList<Model> getList() {

        ArrayList<Model> topics = new ArrayList<>();


        topics.add(new Model(R.drawable.mavzu_1,
                R.drawable.ma_1,
                "Mavzu 1",
                " Humor and satire in W. Shakespeare’s comedies.",
                "Traditionally Shakespeare play types are categorised as Comedy, History, Roman and Tragedy, with some additional categories proposed over the years. Shakespeare comedies (or rather the plays of Shakespeare that are usually categorised as comedies) are generally identifiable as plays full of fun, irony and dazzling wordplay. They also abound in disguises and mistaken identities, with very convoluted plots that are difficult to follow with very contrived endings.\n" +
                        "\n" +
                        "Any attempt at describing Shakespeare’s comedy plays as a cohesive group can’t go beyond that superficial outline. The highly contrived endings of most Shakespeare comedies are the clue to what these plays – all very different – are about.\nTake The Merchant of Venice for example – it has the love and relationship element. As is often the case, there are two couples. One of the women is disguised as a man through most of the text – typical of Shakespearean comedy – but the other is in a very unpleasant situation – a young Jewess seduced away from her father by a shallow, rather dull young Christian. The play ends with the lovers all together, as usual, celebrating their love and the way things have turned out well for their group. That resolution has come about by completely destroying a man’s life.\n" +
                        "\n" +
                        "The Jew, Shylock is a man who has made a mistake and been forced to pay dearly for it by losing everything he values, including his religious freedom. It is almost like two plays – a comic structure with a personal tragedy embedded in it. The ‘comedy’ is a frame to heighten the effect of the tragic elements, which creates something very deep and dark.",
                "Twelfth Night is similar – the humiliation of a man the in-group doesn’t like. As in The Merchant of Venice, his suffering is simply shrugged off in the highly contrived comic ending.Not one of Shakespearean comedy, no matter how full of life and love and laughter and joy, it may be, is without a darkness at its heart. Much Ado About Nothing , like Antony and Cleopatra (a ‘tragedy’ with a comic structure), is a miracle of creative writing. Shakespeare seamlessly joins an ancient mythological love story and a modern invented one, weaving them together into a very funny drama in which light and dark chase each other around like clouds and sunshine on a windy day, and the play threatens to fall into an abyss at any moment and emerges from that danger in a highly contrived ending once again.\n" +
                        "\n" +
                        "Like the ‘tragedies’ Shakespeare comedies defy categorisation. They all draw our attention to a range of human experience with all its sadness, joy, poignancy, tragedy, comedy, darkness and lightness. Below are all of the plays generally regarded as Shakespeare comedy plays.Shakespeare’s Twelfth Night opens with the lovesick, Orsino, Duke of Illyria feeling sorry for himself as his beautiful neighbour, Countess Olivia, has been rejecting his advances. She has sworn to have nothing to do with men for seven years as she plans to spend that time mourning the death of her brother.\n" +
                        "\n" +
                        "On the coast of Illyria there has been a shipwreck. A young woman, Viola, has survived and is stranded on the beach. She has heard reports that her twin brother was drowned in the stormy sea. In spite of her grief, she decides to be positive and seek a job in Illyria. She has heard of the Duke and, with the help of a sea captain she disguises herself as a boy and is appointed as a page in Orsino’s household.")
        );
        topics.add(new Model(R.drawable.m_2,
                R.drawable.ma_2,
                "Mavzu 2",
                " The reflection of heroism in the novels of E.Hemingway.",
                "Hemingway’s Heroism is defined by a fixed set of optimistic characteristics. This distinctiveness remains essentially the same throughout all of Hemingway’s literal works. The Hemingway Hero is always courageous, confident, and thoughtful. He does not let his fears get to him. The Hemingway Hero is expressed differently in each of his novels, though. Sometimes he is young, and sometimes old. In Hemingway’s novels “The Nick Adams Stories” and “The Old Man and the Sea”, the Hero is initiated in a different way. In “The Nick Adams Stories”, Nick Adams begins as a adolescent, young boy then becomes the Hero within the view of the reader as his early life and the occurrences that influenced his life most are the entirety of this memoir-style novel. In “The Old Man and the Sea’, though, the old man does not develop into a hero. Santiago begins as an old man who has already achieved the Heroic qualities that he will exhibit intentionally throughout the rest of the story. Nick, the main character in “The Nick Adams Stories”, is in many ways is like Hemingway himself. Setting up camp and fishing and cooking by himself, Nick lifts his spirits by creating his own personal utopian thought. He remains and is static, unchanging example of Hemingway’s optimistic of heroism. In fact, Nick Adams is probably the most autobiographical sketch of Hemingway’s characters. Instead he relied, like Nick Adams, on finding his own escape from reality, making his own “good place”. Like Nick Adams, Hemingway establishes nature to be the best escape for him from his disturbed world.\n" +
                        "\n" +
                        "In fact to a study of Hemingway in general is the concept of the Hemingway’s hero, sometimes more popularly known as the “code hero.” When Hemingway’s novels first began to appear they were eagerly accepted by the American reading community; in fact, they were passionately received. Part of this reception was due to the fact that Hemingway had shaped a new type of fictional character whose basic response to life appealed very strappingly to the people of the 1920s. At first the average reader saw in the Hemingway’s hero a type of person whom he could recognize with in almost a dream sense.\n" +
                        "\n" +
                        "The present study has been made to portray the Hemingway’s heroism in the light of the tradition of hero-quest, to view him in a heroic prospective. Further it aims at portraying the mythological heroes in their search for identity, where they reflect upon the “essential facts of life,” unlike Hemingway’s quest in his hunting saga “ideals single perfect shot” shares a common narrative pattern is of much significance that goes beyond the individual work. The hero is a human being. He embodies human self-esteem. The later aspect is very strong in the so-called romantic hero, whatever may be the other aspects of his personality, is always a person with a deep sense of dignity.",
                "Closely related to the concept of stoicism is the “Code Hero,” a phrase which is used to describe the main temperament in many of Hemingway’s novels. Some critics regard Santiago in the novel of Old man and the Sea, as the finest, most developed example of these code heroes.In this phrase, “code” means a set of rules or guidelines for conduct. In Hemingway’s code, the principal ideals are honor, courage, and endurance in a life of stress, misfortune, and pain. Often in Hemingway’s stories, the hero’s world is violent and disorderly; moreover, the violence and disorder seem to win.The “code” dictates that the hero act honorably in the midst of what will be a losing battle. In doing so he finds fulfillment: he becomes a man or proves his manhood and his worth. The phrase “grace under pressure” is often used to describe the conduct of the code hero.\n" +
                        "\n" +
                        "Hemingway defined the Code Hero as “a man who lives correctly, following the ideals of honor, courage and endurance in a world that is sometimes chaotic, often stressful, and always painful.” He measures himself by how well he handle the difficult situations that life throws at him. In the end the Code Hero will lose because we are all mortal, but the true measure is how a person faces death. He believes in “Nada,” a Spanish word meaning nothing. Along with this, there is no after life.The Code Hero is typically an individualist and free-willed. He never shows emotions; showing emotions and having a commitment to women shows weakness. Qualities such as bravery, adventuresome and travel also define the Code Hero.\n" +
                        "\n" +
                        "Ironically, the code hero can also be afraid of the dark in that it symbolizes the void, the abyss, the nothingness (nada) that comes with death. However, once he faces death bravely and becomes a man he must continue the struggle and constantly prove himself to retain his manhood.\n" +
                        "\n" +
                        "The code hero or heroine (like Catherine Barkley) must perform his or her work well to create a kind of personal meaning amidst the greater meaninglessness. Still, life is filled with misfortunes, and a code hero is known by how he endures those misfortunes. Ultimately, the code hero will lose in his conflict with life because he will die. But all that matters is how one faces death. In fact, one should court death, in the bull ring, on the battlefield, against big fish, because facing death teaches us how to live. Along with this, the code hero must create and follow certain rituals regarding death because those rituals help us. The bullfighter must have grace and must make his kills clean. He must face noble animals. He must put on his suit a certain way. Similarly, a fisherman shouldn’t go out too far. He should respect the boundaries the fish have established for fishermen. Religion is helpful only in that it provides us with rituals. But religions are wrong when they promise life after death.\n" +
                        "\n" +
                        "If an individual faces death bravely, then he becomes a man, but he must repeat the process, constantly proving himself, until the ultimate defeat. The Hemingway man was a man’s man. He was a man involved in a great deal of drinking. He was a man who moved from one love affair to another, who participated in wild game hunting, who enjoyed bullfights, who was involved in all of the so-called manly activities, which the typical American male did not participate in. Throughout many of Hemingway’s novels the code hero acts in a manner which allowed the critic to formulate a particular code. He does not talk about what he believes in. He is man of action rather than a man of theory.\n" +
                        "\n" +
                        "Behind the formulation of this concept of the hero lies the basic disillusionment brought about by the First World War. The sensitive man came to the realization that the old concepts and the old values embedded in Christianity and other ethical systems of the western world had not served to save mankind from the catastrophe inherent in the World War. A basis for all of the actions of all Hemingway code heroes is the concept of death. The idea of death lies behind all of the character’s actions in Hemingway novels. When you are dead you are dead.There is nothing more. If man cannot accept a life or reward after death, the emphasis must then be on obtaining or doing or performing something in this particular life. If death ends all activity, if death ends all knowledge and consciousness, man must seek his reward here, now, immediately. Consequently, the Hemingway man exists in a large part for the gratification of his sensual desires, he will devote himself to all types of physical happiness because these are the reward of this life.\n" +
                        "\n" +
                        "It is the duty of the Hemingway hero to avoid death at almost all cost. Life must continue. Life is valuable and enjoyable. Life is everything. Death is nothing. With this view in mind it might seem strange then to the casual or superficial reader that the Hemingway code hero will often be placed in an encounter with death, or that the Hemingway hero will often choose to confront death. From this we derive the idea of grace (or courage) under pressure. This concept is one according to which the character must act in a way that is acceptable when he is faced with the fact of death. The Hemingway man must have fear of death, but he must not be afraid to die. By fear we mean that he must have the intellectual realization that death is the end of all things and as such must be constantly avoided in one way or another. A man can never act in a cowardly way. He must not show that he is afraid or trembling or frightened in the presence of death. If man wishes to live, he lives most intensely sometimes when he is in the direct presence of death. The man has not yet been tested; we don’t know whether he will withstand the pressures, whether he will prove to be a true Hemingway man. It is only by testing, by coming into confrontation with something that is dangerous that man lives with this intensity. In the presence of death, then, man can discover his own sense of being, his own potentiality.")
        );
        topics.add(new Model(R.drawable.maa1,
                R.drawable.maa2,
                "Mavzu 3",
                "  Christopher Marlowe’s “Carp Diem Poetry”.",
                "Christopher Marlowe, also known as Kit Marlowe (26 February 1564 – 30 May 1593), was an English playwright, poet and translator of the Elizabethan era. Marlowe is among the most famous of the Elizabethan playwrights. Based upon the \"many imitations\" of his play Tamburlaine, modern scholars consider him to have been the foremost dramatist in London in the years just before his mysterious early death. Some scholars also believe that he greatly influenced William Shakespeare, who was baptised in the same year as Marlowe and later succeeded him as the pre-eminent Elizabethan playwright. Marlowe was the first to achieve critical reputation for his use of blank verse, which became the standard for the era. His plays are distinguished by their overreaching protagonists. Themes found within Marlowe's literary works have been noted as humanistic with realistic emotions, which some scholars find difficult to reconcile with Marlowe's \"anti-intellectualism\" and his catering to the prurient tastes of his Elizabethan audiences for generous displays of extreme physical violence, cruelty, and bloodshed.\n" +
                        "\n" +
                        "Events in Marlowe's life were sometimes as extreme as those found in his plays. Differing sensational reports of Marlowe's death in 1593 abounded after the event and are contested by scholars today owing to a lack of good documentation. There have been many conjectures as to the nature and reason for his death, including a vicious bar-room fight, blasphemous libel against the church, homosexual intrigue, betrayal by another playwright, and espionage from the highest level: the Privy Council of Elizabeth I. An official coroner's account of Marlowe's death was revealed only in 1925, and it did little to persuade all scholars that it told the whole story, nor did it eliminate the uncertainties present in his biography.",
                "The seventeenth century love poetry has been well known with some of love and lyric poets with the concept of Carpe Diem in their great works. The Carpe Diem concept in Carpe Diem poetry stresses the idea to seize the day due to the shortness of life in order to persuade the addressee to take action while they still have a chance.\n Life should be lived to the fullest everyday, just like it was going to be the last. The ideas of aging, decay, and death are included in order to underscore the urgenc y of the situation or to play upon the addressee?s fears. The concept of Carpe Diem interests me so that I choose to find out in what way it is expressed by some of the seventeenth century poets. \nThey are John Donne in \"The Anniversary\", Andrew Marvell in \"To His Coy Mistress\", Ben Jonson in \"Song: To Celia I (Come, my Celia, let us prove)\" and Robert Herrick in \"To the Virgins to Make Much of Time\" and \"Corinna?s Going A-Maying.\" To find out how each poet in those poems delivers the Carpe Diem concept in their own ways, I collect data by using library and Internet researches. \nI also use literary approach and employ literary tools to do the analysis. After doing the analysis of those five poems, I find out that the poets use the elements of poetry such as diction or the choice of words, imagery, tone, allusion, figures of speech including irony, metaphor, simile, personification, symbol, hyperbole, understatement, synecdoche, and metonymy. \nThey are used by each poet in the poems to show that the Carpe Diem concept focuses on time; by giving a sense that life is short and time is fleeting so that taking chances in life should be done then.")
        );
        topics.add(new Model(R.drawable.m_4,
                R.drawable.ma_4,
                "Mavzu 4",
                " Problems of childhood and education in Ch.Dickens’ works.",
                "Dickens was individually aware of the exploitation to which the children were subjected because of his own history at workhouse. His work house experience parallels Oliver’s work house experience. Children were exploited and forced to work under harsh circumstances. The Victorian society, mainly the middle class, believed in strong moral values and morals. However, they did not do anything on larger scale to help them or change their condition. Children were susceptible to mistreatment. Dickens successfully portrayed the cruelty of children in the nineteenth century Britain. He evoked readers’ sympathy to the terrible conditions of children.\n" +
                        "\n" +
                        "Economic development was led by the Industrial Revolution which began in the middle of the eighteenth century, but it became the cause of many social problems.\n One of the major problems was an increase in child labour. Financial condition of working class people was miserable to an extent that the whole family, even women and children, had to work to add family’s income. Families thought that if they had more children, there would be more hands to work. Child labour became a part of industrialization and various laws were introduced to prohibit it.\n However, child labour existed even before the Industrial Revolution had started. With the advent of the Industrial Revolution, the working class children helped their parents in household chores and farming.\n They helped in different kinds of work as stated, “when in the late eighteenth century, industrialization began to shift the location of the textile industries from home to factory; it was natural to look for children as a key component of the workforce.”\n Instead of labouring in fields or at homes, children preferred working in factories and mines because they were better paid in factories or mines. Many children started working at the very young age because their families relied on their income.\n They had to work for long hours to earn money. As Cunningham wrote, “children often started to work under the age of ten, and the Industrial Revolution period began to regain the reputation it had until recent years as a black moment in the history of childhood.”",
                "Wilson also argues about the child labour perception in the Victorian period. In The Victorians, He explains that most children in the industrial Britain worked along their parents as many hours as their parents did. Children were considered a cheap labour who could work in unpleasant and dangerous places such as mills, factories and coalmines.\n" +
                        "\n" +
                        "Children and orphans were child labour because most of them worked generally for food and accommodation. They did not work for wages. They worked inside the region of a workhouse and had to follow the rules of workhouses strictly. They were also sold to new employers for money. We find the practice of selling children to employers and their poor miserable condition in Oliver Twist. Oliver disobeyed the rules of the workhouse in which he lived. When he asked for more food, a bill was pasted outside the gate offering a reward of five pounds to anybody who would take Oliver. In other words, five pounds and Oliver were offered to any man or woman who wanted an apprentice for any trade, business, or calling.\n" +
                        "\n" +
                        "It is not the only case of Oliver but many other boys to whom master finds that he can acquire sufficient work without giving him much food. The master shall have a child labour for a term of years, to do what he likes with. Industrial Revolution contributed significantly to promote child labour. During this time period, there were inadequate educational opportunities for children; therefore, it was better for them to work. Child labour was an essential part of the method as the children were paid less than adults. They worked under poor conditions for long hours with poor lighting, without proper ventilation and lack of protective clothing. However, there was a little improvement in the condition of child labour with the enactment of factory act in 1864. The act predetermined that no child would be employed under the age of twelve as a factory worker.\n" +
                        "\n" +
                        "The exploitation of children in factories can be seen in Oliver Twist when the man in the white waistcoat wants to sell Oliver to Gamfield as a chimney sweeper. Later on, Oliver is sold to Mr. Sowerberry, the undertaker, and is given the role of a funeral mute. The Industrial Revolution was a period in which many children were working at the workhouses due to poverty like the orphaned Oliver who was assigned to pick oakum at six every morning. Oliver experience raises many questions about the life of children during Victorian age.")
        );
        topics.add(new Model(R.drawable.m_5,
                R.drawable.ma_5,
                "Mavzu 5",
                "Walter Scott – a founder of a genre of a historical novel in English literature.",
                "Walter Scott was born on 15 August 1771, in a third-floor apartment on College Wynd in the Old Town, Edinburgh, a narrow alleyway leading from the Cowgate to the gates of the University of Edinburgh (Old College). He was the ninth child (six having died in infancy) of Walter Scott (1729–1799), a member of a cadet branch of the Clan Scott and a Writer to the Signet, by his wife Anne Rutherford, a sister of Daniel Rutherford and a descendant of both the Clan Swinton and the Haliburton family (the descent from which granted Walter's family the hereditary right of burial in Dryburgh Abbey). Walter was thus a cousin of the property developer James Burton (died 1837), born \"Haliburton\", and of his son the architect Decimus Burton. Walter subsequently became a member of the Clarence Club, of which the Burtons were also members.\n" +
                        "\n"+
                        "Scott's childhood at Sandyknowes, in the shadow of Smailholm Tower, introduced him to the tales and folklore of the Scottish Borders\n" +
                        "The Scott family's home in George Square, Edinburgh, from about 1778\n" +
                        "A childhood bout of polio in 1773 left Scott lame,[7] a condition that would much affect his life and writing. To improve his lameness he was sent in 1773 to live in the rural Scottish Borders, at his paternal grandparents' farm at Sandyknowe, by the ruin of Smailholm Tower, the earlier family home. Here he was taught to read by his aunt Jenny Scott and learned from her the speech patterns and many of the tales and legends that later marked much of his work. In January 1775, he returned to Edinburgh, and that summer with his aunt Jenny took spa treatment at Bath in Somerset, Southern England, where they lived at 6 South Parade. In the winter of 1776, he went back to Sandyknowe, with another attempt at a water cure at Prestonpans the following summer.\n" +
                        "\n" +
                        "In 1778, Scott returned to Edinburgh for private education to prepare him for school and joined his family in their new house, one of the first to be built in George Square. In October 1779, he began at the Royal High School in Edinburgh (in High School Yards). He was by then well able to walk and explore the city and the surrounding countryside. His reading included chivalric romances, poems, history and travel books. He was given private tuition by James Mitchell in arithmetic and writing, and learned from him the history of the Church of Scotland with emphasis on the Covenanters. In 1783, his parents, believing he had outgrown his strength, sent him to stay for six months with his aunt Jenny at Kelso in the Scottish Borders: there he attended Kelso Grammar School, where he met James Ballantyne and his brother John, who later became his business partners and printers.\n" +
                        "\n" +
                        "As a result of his early polio infection, Scott had a pronounced limp. He was described in 1820 as \"tall, well formed (except for one ankle and foot which made him walk lamely), neither fat nor thin, with forehead very high, nose short, upper lip long and face rather fleshy, complexion fresh and clear, eyes very blue, shrewd and penetrating, with hair now silvery white\". Although a determined walker, he experienced greater freedom of movement on horseback.\n" +
                        "\n" +
                        "Scott began studying classics at the University of Edinburgh in November 1783, at the age of 12, a year or so younger than most fellow students. In March 1786, aged 14, he began an apprenticeship in his father's office to become a Writer to the Signet. At school and university Scott had become a friend of Adam Ferguson, whose father Professor Adam Ferguson hosted literary salons. Scott met the blind poet Thomas Blacklock, who lent him books and introduced him to the Ossian cycle of poems by James Macpherson. During the winter of 1786–1787, a 15-year-old Scott met the Scots poet Robert Burns at one of these salons, their only meeting. When Burns noticed a print illustrating the poem \"The Justice of the Peace\" and asked who had written it, Scott alone named the author as John Langhorne and was thanked by Burns. Scott describes the event in his memoirs, where he whispers the answer to his friend Adam, who tells Burns; another version of the event appears in Literary Beginnings. When it was decided that he would become a lawyer, he returned to the university to study law, first taking classes in moral philosophy (under Dugald Stewart) and universal history (under Alexander Fraser Tytler) in 1789–1790. During this second university spell Scott became prominent in student intellectual activities: he co-founded the Literary Society in 1789 and was elected to the Speculative Society the following year, becoming librarian and secretary-treasurer a year after.\n" +
                        "\n" +
                        "After completing his law studies, Scott took up law in Edinburgh. He made his first visit as a lawyer's clerk to the Scottish Highlands, directing an eviction. He was admitted to the Faculty of Advocates in 1792. He had an unsuccessful love suit with Williamina Belsches of Fettercairn, who married Scott's friend Sir William Forbes, 7th Baronet. In February 1797, the threat of a French invasion persuaded Scott and many of his friends to join the Royal Edinburgh Volunteer Light Dragoons, where he served into the early 1800s, and was appointed quartermaster and secretary. The daily drill practices that year, starting at 5 a.m., indicate the determination with which the role was undertaken.",
                "Scott was prompted to take up a literary career by enthusiasm in Edinburgh in the 1790s for modern German literature. Recalling the period in 1827, Scott said that he \"was German-mad.\" In 1796, he produced English versions of two poems by Gottfried August Bürger, Der wilde Jäger and Lenore, published as The Chase, and William and Helen. Scott responded to the German interest at the time in national identity, folk culture and medieval literature, which linked with his own developing passion for traditional balladry. A favourite book since childhood had been Thomas Percy's Reliques of Ancient English Poetry. During the 1790s he would search in manuscript collections and on Border \"raids\" for ballads from oral performance. With help from John Leyden, he produced a two-volume Minstrelsy of the Scottish Border in 1802, containing 48 traditional ballads and two imitations apiece by Leyden and himself. Of the 48 traditionals, 26 were published for the first time. An enlarged edition appeared in three volumes the following year. With many of the ballads, Scott fused different versions into more coherent texts, a practice he later repudiated.[16] The Minstrelsy was the first and most important of a series of editorial projects over the next two decades, including the medieval romance Sir Tristrem (which Scott attributed to Thomas the Rhymer) in 1804, the works of John Dryden (18 vols, 1808), and the works of Jonathan Swift (19 vols, 1814).\n" +
                        "\n" +
                        "On a trip to the English Lake District with old college friends, he met Charlotte Charpentier (Anglicised to \"Carpenter\"), a daughter of Jean Charpentier of Lyon in France and a ward of Lord Downshire in Cumberland, an Anglican. After three weeks' courtship, Scott proposed and they were married on Christmas Eve 1797 in St Mary's Church, Carlisle (now the nave of Carlisle Cathedral). After renting a house in Edinburgh's George Street, they moved to nearby South Castle Street. Their eldest child, Sophia, was born in 1799, and later married John Gibson Lockhart. Four of their five children survived Scott himself. His eldest son Sir Walter Scott, 2nd Baronet (1801–1847), inherited his father's estates and possessions: on 3 February 1825 he married Jane Jobson, only daughter of William Jobson of Lochore (died 1822) by his wife Rachel Stuart (died 1863), heiress of Lochore and a niece of Lady Margaret Ferguson. In 1799 Scott was appointed Sheriff-Depute of the County of Selkirk, based in the Royal Burgh of Selkirk. In his early married days Scott earned a decent living from his work as a lawyer, his salary as Sheriff-Depute, his wife's income, some revenue from his writing, and his share of his father's modest estate.")
        );
        topics.add(new Model(R.drawable.m_6,
                R.drawable.ma_6,
                "Mavzu 6",
                "Women-writers in English literature.",
                "Maya Angelou. Maya Angelou was born in 1928 in Missouri.\n" +
                        "Maya Angelou (born Marguerite Annie Johnson; April 4, 1928 – May 28, 2014) was an American poet, memoirist, and civil rights activist. She published seven autobiographies, three books of essays, several books of poetry, and is credited with a list of plays, movies, and television shows spanning over 50 years. She received dozens of awards and more than 50 honorary degrees. Angelou is best known for her series of seven autobiographies, which focus on her childhood and early adult experiences. The first, I Know Why the Caged Bird Sings (1969), tells of her life up to the age of 17 and brought her international recognition and acclaim" +
                        "\n"+
                        "Beverly Cleary.\n" +
                        "Beverly Atlee Cleary (April 12, 1916 – March 25, 2021) was an American writer of children's and young adult fiction. One of America's most successful authors, 91 million copies of her books have been sold worldwide since her first book was published in 1950. Some of her best known characters are Ramona Quimby and Beezus Quimby, Henry Huggins and his dog Ribsy, and Ralph S. Mouse.\n" +
                        "\n" +
                        "The majority of Cleary's books are set in the Grant Park neighborhood of northeast Portland, Oregon, where she was raised, and she has been credited as one of the first authors of children's literature to figure emotional realism in the narratives of her characters, often children in middle-class families. Her first children's book was Henry Huggins after a question from a kid when Cleary was a librarian. Cleary won the 1981 National Book Award for Ramona and Her Mother and the 1984 Newbery Medal for Dear Mr. Henshaw." +
                        "\n"+
                        "Willa Cather.\n" +
                        "Willa Sibert Cather ( born Wilella Sibert Cather; December 7, 1873 – April 24, 1947) was an American writer known for her novels of life on the Great Plains, including O Pioneers!, The Song of the Lark, and My Ántonia. In 1923, she was awarded the Pulitzer Prize for One of Ours, a novel set during World War I." +
                        "\n"+
                        "Sandra Cisneros.\n" +
                        "Sandra Cisneros (born December 20, 1954) is an American writer. She is best known for her first novel, The House on Mango Street (1983), and her subsequent short story collection Woman Hollering Creek and Other Stories (1991). Her work experiments with literary forms that investigate emerging subject positions, which Cisneros herself attributes to growing up in a context of cultural hybridity and economic inequality that endowed her with unique stories to tell. She is the recipient of numerous awards, including a National Endowment for the Arts Fellowship, was awarded one of 25 new Ford Foundation Art of Change fellowships in 2017, and is regarded as a key figure in Chicana literature." +
                        "\n"+
                        "Toni Morrison.\n" +
                        "Chloe Anthony Wofford Morrison (born Chloe Ardelia Wofford; February 18, 1931 – August 5, 2019), known as Toni Morrison, was an American novelist. Her first novel, The Bluest Eye, was published in 1970. The critically acclaimed Song of Solomon (1977) brought her national attention and won the National Book Critics Circle Award. In 1988, Morrison won the Pulitzer Prize for Beloved (1987); she was awarded the Nobel Prize in Literature in 1993.",
                "As time passes literature reflects this phenomenon in many ways. Themes and characters shift to reflect the period. Attitudes and literary devices provide perspective on writer’s emotional state often as a result of outside influences. Format may move from formal to less structured. Most evident of the changes to literary works as years go by is the language. Each era has a linguistic system all its own. The study of linguistics reveals how these changes occur, often slowly over time, and as a result of social use and diction preferences, such as dialect shifts, colloquialism and slang prominence, and the acceptance of new words. Literature serves as a map of those changes. The great female writers of English literature provide language in their works that reveal the social influence and artistic preferences for each age. The works of modern and post-modern authors, such as Alice Munro and Anne Carson, may share common themes with Victorian and Romantic authors, such as Emily Bronte and Mary Wollstonecraft, but the language of the pieces are quite different.\n" +
                        "Female authors were a bit of a rarity in Britain when they first appeared in the early 18th century when the novel became established as a central literary form in Britain. It then had an ideology of sensibility and benevolence. Women had an active role in the development of fiction which was hardly surprising as they were the main readers of it! Their inspiration came from life in city and village, experiences of travel, love and marriage, religion or education. The idea of the novel came from Europe, and novel is from the Italian “novella” meaning new.\n" +
                        "\n" +
                        "One of the chief founders was Aphra Behn (1640-89) born in Canterbury and who died in London. This lady from the Restoration era was one of the first English women to earn an income as an author breaking cultural barriers to become a leading literary role for generations of other women authors. She married a Dutch merchant in London who died the same year, spied in Antwerp for King Charles II and travelled to Surinam where she allegedly met an African slave leader. He became her inspiration for Oroonoko in 1688 which was an anti-slavery critique tinted with feminism and post-colonialism. This book is believed to be one of the first abolitionist and humanitarian novels printed in English and the first anti-slavery novel.  In her time, she was esteemed as a poet, a leading playwright and author of satirical London. She included female pleasure and sexuality in her poetry, very radical at the time, and cause for much criticism during her life and after her death. Her poem Disappointment is a comic account of male impotency from a female point of view – totally outrageous for her time.")
        );
        topics.add(new Model(R.drawable.ma_7,
                R.drawable.m_7,
                "Mavzu 7",
                "Critical realism in English literature of the XIX.",
                "The 19th century was characterized by sharp contradictions. In many ways it was an age of progress: railways and ships were built, great scientific discoveries were made, education became more widespread; but al the same time it was an age of profound social unrest, because there was too much poverty, too much injustice. The growth of scientific inventions mechanized industry and increased wealth, but this progress only enriched the few at the expense of the many. Dirty factories, long hours of work, child labour, exploitation, low wages, slums and frequent unemployment -these were the conditions of life for the workers in the growing industries of England, which became the richest country in the world towards the middle of the 19th century.\n" +
                        "By the thirties of the 19th century English capitalism had entered a new stage of development. England had become a classical capitalist country, a country of industrial capitalism. The Industrial Revolution gathered force as the 19th century progressed, and profound changes in hand-looms gave way, within a hundred years, to factory towns, railroads, and steamships. The population of Manchester, Birmingham and other industrial centres was growing rapidly as the number of factory workers increased, while the number of poor farmers decreased and many rural districts were depopulated. The basic social classes in England were no longer the peasants and the landlords but the proletariat and the bourgeoisie.\n" +
                        "Having won the victory over aristocracy, the bourgeoisie betrayed the interests of the working class. The workers fought for their rights. Their political demands were expressed in the People's Charier in 1833. The Chartis Movement was a revolutionary movement of the English workers, which lasted till 1848.\n" +
                        "The Chartists introduced their own literature, which was the first attempt to create a literature of the working class. The Chartist writers tried their hand at different genres. They wrote articles, short stories, songs, epigrams, poems. Their leading genre was poetry.\n" +
                        "The ideas of the Chartism attracted the attention of many progressive-minded people of that time. A lot of prominent writers became aware of the social injustices around them and tried to depict them in their works. Thus this period was mirrored in literature by the appearance of a new trend, the Critical Realism. The greatest novelists of the age are Charles Dickens, William Makepeace Thackeray, Charlotte Bronte, Elizabeth Gaskell.\n" +
                        "These writers used the novel as a means to protest against the evils in contemporary social and economic life and to picture the world in a realistic way. Their greatness also lies in their profound humanism. Their sympathy lies with the ordinary people. They believed in the good qualities of the human heart.",
                "William Makepeace Thackeray (1811-1863)\n" +
                        "\n" +
                        "This author was born in Calcutta, where his father was employed in the East India company. When he was 6, he was sent to England and was educated at Charter-house school. Then he studied at Trinity College Ireland and then at Cambridge. He spent some month in Weimar studying art. In search of a career he began to read for the bar (jurisdiction). But he didnt find law much to his taste. Later he studied drawing and became an able droughts-man (шаржист). He even published a collection of satirical drawings \"Zephyr\" (1836).\n" +
                        "\n" +
                        "Thackeray started his literary career as a journalist writing stories, reviews and art criticism. The first major book attracted attention was “The Book of Snobs”, which deals with the upper classes and their ardent (passionate) followers in the middle classes. The book draws a gallery of English snobs of different circles of English society. A snob according to Thackeray is a person who bows down to and flatters his social superior and looks down with contempt (презирать) on his social inferior. In the book the author declares war on snobbery, vanity and selfishness. It is no surprise that the book of snobs was follower by and even sharper devoted to the same thing\n" +
                        "\n" +
                        "“The Vanity Fair” (Ярмарка тщеславия). A Novel without a Hero - considered to be the pick of social realism.\n" +
                        "\n" +
                        "The novel tells of the fates of 2 girls with sharply contrasting characters, Becky Sharp and Amelia Sedley. Amelia is a sweet honest, naive young girl, representing virtue without wit. Her friend Rebecca Sharp is clever, talented, charming, energetic girl, representing wit without virtue. Neither of the girls can be regarded as a heroine of the novel. Becky has neither real feeling nor honest aims. Amelia is too intelligent naive and simple hearted to understand qualities of the people surrounding her.\n" +
                        "\n" +
                        "Vanity Fair was followed by “The History of Pendennis” (1848) and “The Newcomers” (1855). The novels of the later period of Thackerays creative activity are “Henry Esmond” and “The Virginians”, displaying his preoccupation with the social problems of that time.\n")

        );
        topics.add(new Model(R.drawable.m_8,
                R.drawable.ma_8,
                "Mavzu 8",
                "The Second World War in American literature.",
                " World War II gave a new direction to literary development in the United States. “Anything not connected with the war must be postponed,” was the chief unwritten law of the wartime era.\n" +
                        "\n" +
                        "Moreover, the war drastically reduced the productivity of all writers. As W. Faulkner remarked, “you don’t write well in war.” Many writers were at the front as war correspondents (like E. Hemingway) or in the active army (like J. Cheever, S. Bellow, N. Mailer, C. Vonnegut), and they naturally had no time for artistic creativity. Most importantly, however, both they and those who remained in America needed first to comprehend this newly changed world and the place that man occupied in it. Genocide and the possibility of total nuclear annihilation affected not only European Jews and Japanese, but all people on both sides of the globe, destroying the last vestiges of national American naivety and “innocence.\n" +
                        "\n" +
                        "The end of the previous period of U.S. literary development was vividly underscored by the deaths of several major writers of the 20s and 30s: Scott Fitzgerald and Nathaniel West were gone in 1940, S. Anderson passed away in 1941, and G. Stein in 1946. The era of modernism is gone, although its greatest representatives – E. Hemingway and W. Faulkner – still continued to create.\n" +
                        "\n" +
                        "With the end of the war in the national literature came a new generation of young writers with honest realistic works about their tragic experience. The writers who first gave a reflection of World War II in American prose were J. Hersey (Hiroshima, 1946), N. Mailer (Naked and Dead, 1948), I. Shaw (The Young Lions, 1948), G. Wook (The Caine Conspiracy, 1951), J. Jones (From Here and Forever, 1951) and other “war novelists”, as critics defined them. M. Cowley lamented at the time that, unlike the First World War, which produced a vivid literary experiment, the Second brought to life only the most traditional realism. Very soon, however, it became clear that Cowley had been somewhat hasty in his judgments.\n" +
                        "\n" +
                        "After World War II, Jewish-American literature came into the national spotlight. Its authors spoke as if they were speaking on behalf of millions of European Jews who were victims of genocide to whom they owed a debt of blood. They had yet to make sense of this monstrous historical experience. It is telling that the most impressive works about the genocide did not come out until the 1970s: Singer’s Shosha, Epstein’s The King of the Jews, Bellow’s Mr. Samler’s Planet. In the meantime, it was necessary to rethink the unique experience of American Jewry.",
                "Since the mid-1940s there has been an incredible flowering of Jewish-American literature – poetry, drama and, especially, prose. It is at this time that the work of J.B. Singer becomes a fact of American literature, the World War I-born S. Bellow, A. Miller, and later B. Malamud and writers of the next generation (born in the 20s and 30s): Philip Roth, Norman Mailer, Herbert Gold, Joseph Heller, Edgar Lawrence Doctorow, Grace Paley, Leslie Epstein and many others begin to publish. Most are postmodern writers.\n" +
                        "\n" +
                        "Postwar Jewish-American literature is distinguished from earlier literature by a special sense of history, heightened by the tragic experience of Jewishness. Associated with the sense of historical instability is the desire of the postwar generation of Jewish-American writers not only for religious, political, or ethnic self-definition, but above all for existential self-definition: “What does it mean to be human?”\n" +
                        "\n" +
                        "Not surprisingly, the most striking and yet very diverse works in U.S. literature about World War II, a time that devalued the human person to the utmost, were written by Jewish-American writers. Norman Mailer’s novel The Naked and the Dead (1948), for example, stunned readers with the poignant authenticity of direct war testimony. “Joseph Heller’s Amendment-22 (1961) presented the war and everyday life of the “heroic” American army as utterly absurd, eliciting Homeric laughter and bitter doubts about the sanity of the world order as a whole.\n" +
                        "\n" +
                        "Isaac Bashevis Singer’s (1904-1991) novel Shosha (1978), which shook America as a reflection on the catastrophic madness of genocide, was also a book about the tragedy of modern man, whose mystery of existence is dark to him, because the path of salvation he seeks, he is essentially searching blindly. The author sees the only answer to the nonsense of historical catastrophe in the fatal loyalty of man to his human destiny. This fidelity is embodied by Singer in the image of the blessed “foolish girl” Shosha.")
        );
        topics.add(new Model(R.drawable.ma_9,
                R.drawable.m_9,
                "Mavzu 9",
                " Langston Hughes and his poetry.",
                "James Mercer Langston Hughes (February 1, 1901 – May 22, 1967) was an American poet, social activist, novelist, playwright, and columnist from Joplin, Missouri. One of the earliest innovators of the literary art form called jazz poetry, Hughes is best known as a leader of the Harlem Renaissance. He famously wrote about the period that \"the Negro was in vogue\", which was later paraphrased as \"when Harlem was in vogue.\"\n" +
                        "\n" +
                        "Growing up in a series of Midwestern towns, Hughes became a prolific writer at an early age. He moved to New York City as a young man, where he made his career. He graduated from high school in Cleveland, Ohio, and soon began studies at Columbia University in New York City. Although he dropped out, he gained notice from New York publishers, first in The Crisis magazine, and then from book publishers and became known in the creative community in Harlem. He eventually graduated from Lincoln University. In addition to poetry, Hughes wrote plays, and short stories. He also published several non-fiction works. From 1942 to 1962, as the civil rights movement was gaining traction, he wrote an in-depth weekly column in a leading black newspaper, The Chicago Defender.\n" +
                        "Like many African-Americans, Hughes had a complex ancestry. Both of Hughes' paternal great-grandmothers were enslaved Africans, and both of his paternal great-grandfathers were white slave owners in Kentucky. According to Hughes, one of these men was Sam Clay, a Scottish-American whiskey distiller of Henry County, said to be a relative of statesman Henry Clay. The other putative paternal ancestor whom Hughes named was Silas Cushenberry, a slave trader of Clark County. Hughes wrote that Cushenberry was a Jewish slave trader, but a study of the Cushenberry family genealogy in the nineteenth century has found no Jewish affiliation. Hughes's maternal grandmother Mary Patterson was of African-American, French, English and Native American descent. One of the first women to attend Oberlin College, she married Lewis Sheridan Leary, also of mixed race descent, before her studies. Lewis Leary subsequently joined John Brown's raid on Harpers Ferry in West Virginia in 1859, where he was fatally wounded.\n" +
                        "\n" +
                        "Ten years later, in 1869, the widow Mary Patterson Leary married again, into the elite, politically active Langston family. (See The Talented Tenth.) Her second husband was Charles Henry Langston, of African-American, Euro-American and Native American ancestry. He and his younger brother John Mercer Langston worked for the abolitionist cause and helped lead the Ohio Anti-Slavery Society in 1858.\n" +
                        "\n" +
                        "After their marriage, Charles Langston moved with his family to Kansas, where he was active as an educator and activist for voting and rights for African Americans. His and Mary's daughter Caroline (known as Carrie) became a schoolteacher and married James Nathaniel Hughes (1871–1934). They had two children; the second was Langston Hughes, by most sources born in 1901 in Joplin, Missouri (though Hughes himself claims in his autobiography to have been born in 1902)",
                "First published in 1921 in The Crisis — official magazine of the National Association for the Advancement of Colored People (NAACP) — \"The Negro Speaks of Rivers\" became Hughes's signature poem and was collected in his first book of poetry, The Weary Blues (1926). Hughes's first and last published poems appeared in The Crisis; more of his poems were published in The Crisis than in any other journal. Hughes' life and work were enormously influential during the Harlem Renaissance of the 1920s, alongside those of his contemporaries, Zora Neale Hurston, Wallace Thurman, Claude McKay, Countee Cullen, Richard Bruce Nugent, and Aaron Douglas. Except for McKay, they worked together also to create the short-lived magazine Fire!! Devoted to Younger Negro Artists.\n" +
                        "\n" +
                        "Hughes and his contemporaries had different goals and aspirations than the black middle class. Hughes and his fellows tried to depict the \"low-life\" in their art, that is, the real lives of blacks in the lower social-economic strata. They criticized the divisions and prejudices within the black community based on skin color. Hughes wrote what would be considered their manifesto, \"The Negro Artist and the Racial Mountain\", published in The Nation in 1926:\n" +
                        "\n" +
                        "The younger Negro artists who create now intend to express our individual dark-skinned selves without fear or shame. If white people are pleased we are glad. If they are not, it doesn't matter. We know we are beautiful. And ugly, too. The tom-tom cries, and the tom-tom laughs. If colored people are pleased we are glad. If they are not, their displeasure doesn't matter either. We build our temples for tomorrow, strong as we know how, and we stand on top of the mountain free within ourselves.\n" +
                        "\n" +
                        "His poetry and fiction portrayed the lives of the working-class blacks in America, lives he portrayed as full of struggle, joy, laughter, and music. Permeating his work is pride in the African-American identity and its diverse culture. \"My seeking has been to explain and illuminate the Negro condition in America and obliquely that of all human kind\", Hughes is quoted as saying. He confronted racial stereotypes, protested social conditions, and expanded African America's image of itself; a \"people's poet\" who sought to reeducate both audience and artist by lifting the theory of the black aesthetic into reality.\n" +
                        "Hughes stressed a racial consciousness and cultural nationalism devoid of self-hate. His thought united people of African descent and Africa across the globe to encourage pride in their diverse black folk culture and black aesthetic. Hughes was one of the few prominent black writers to champion racial consciousness as a source of inspiration for black artists. His African-American race consciousness and cultural nationalism would influence many foreign black writers, including Jacques Roumain, Nicolás Guillén, Léopold Sédar Senghor, and Aimé Césaire. Along with the works of Senghor, Césaire, and other French-speaking writers of Africa and of African descent from the Caribbean, such as René Maran from Martinique and Léon Damas from French Guiana in South America, the works of Hughes helped to inspire the Négritude movement in France. A radical black self-examination was emphasized in the face of European colonialism. In addition to his example in social attitudes, Hughes had an important technical influence by his emphasis on folk and jazz rhythms as the basis of his poetry of racial pride.\n" +
                        "\n" +
                        "In 1930, his first novel, Not Without Laughter, won the Harmon Gold Medal for literature. At a time before widespread arts grants, Hughes gained the support of private patrons and he was supported for two years prior to publishing this novel. The protagonist of the story is a boy named Sandy, whose family must deal with a variety of struggles due to their race and class, in addition to relating to one another.\n" +
                        "\n" +
                        "In 1931, Hughes helped form the \"New York Suitcase Theater\" with playwright Paul Peters, artist Jacob Burck, and writer (soon-to-be underground spy) Whittaker Chambers, an acquaintance from Columbia. In 1932, he was part of a board to produce a Soviet film on \"Negro Life\" with Malcolm Cowley, Floyd Dell, and Chambers.\n" +
                        "\n" +
                        "In 1931 Prentiss Taylor and Langston Hughes created the Golden Stair Press, issuing broadsides and books featuring the artwork of Prentiss Taylor and the texts of Langston Hughes. In 1932 they issued The Scottsboro Limited based on the trial of the Scottsboro Boys")
        );
        topics.add(new Model(R.drawable.ma_11,
                R.drawable.m_11,
                "Mavzu 10",
                " English romanticism and its development.",
                "Romanticism was an artistic, literary, and intellectual movement that originated in Europe toward the end of the 18th century. Scholars regard the publishing of William Wordsworth's and Samuel Coleridge's Lyrical Ballads in 1798 as probably the beginning of the movement, and the crowning of Queen Victoria in 1837 as its end. Romanticism arrived in other parts of the English-speaking world later; in America, it arrived around 1820.\n" +
                        "\n" +
                        "The Romantic period was one of major social change in England, due to depopulation of the countryside and rapid development of overcrowded industrial cities that took place roughly between 1798 and 1832. The movement of so many people in England was the result of two forces: the Agricultural Revolution, which involved enclosures that drove workers and their families off the land, and the Industrial Revolution which provided them employment, \"in the factories and mills, operated by machines driven by steam-power\". Indeed, Romanticism may be seen in part as a reaction to the Industrial Revolution, though it was also a revolt against aristocratic social and political norms of the Age of Enlightenment, as well as a reaction against the scientific rationalization of nature. The French Revolution was an especially important influence on the political thinking of many notable Romantic figures at this time as well.\n" +
                        "The Romantic movement in English literature of the early 19th century has its roots in 18th-century poetry, the Gothic novel and the novel of sensibility. This includes the graveyard poets, who were a number of pre-Romantic English poets writing in the 1740s and later, whose works are characterized by their gloomy meditations on mortality, \"skulls and coffins, epitaphs and worms\" in the context of the graveyard. To this was added by later practitioners, a feeling for the \"sublime\" and uncanny, and an interest in ancient English poetic forms and folk poetry. These concepts are often considered precursors of the Gothic genre. Some major Gothic poets include Thomas Gray (1716–71), whose Elegy Written in a Country Churchyard (1751) is \"the best known product of this kind of sensibility\"; William Cowper (1731–1800); Christopher Smart (1722–71); Thomas Chatterton (1752–70); Robert Blair (1699–1746), author of The Grave (1743), \"which celebrates the horror of death\"; and Edward Young (1683–1765), whose The Complaint, or Night-Thoughts on Life, Death and Immortality (1742–45) is another \"noted example of the graveyard genre\". Other precursors of Romanticism are the poets James Thomson (1700–48) and James Macpherson (1736–96).\n" +
                        "\n" +
                        "The sentimental novel or \"novel of sensibility\" is a genre which developed during the second half of the 18th century. It celebrates the emotional and intellectual concepts of sentiment, sentimentalism and sensibility. Sentimentalism, which is to be distinguished from sensibility, was a fashion in both poetry and prose fiction which began in reaction to the rationalism of the Augustan Age. Sentimental novels relied on emotional response both from their readers and characters. Scenes of distress and tenderness are common, and the plot is arranged to advance emotions rather than action. The result is a valorization of \"fine feeling\", displaying the characters as models for refined, sensitive emotional effect. The ability to display feelings was thought to show character and experience, and to shape social life and relations. Among the most famous sentimental novels in English are Samuel Richardson's Pamela, or Virtue Rewarded (1740), Oliver Goldsmith's The Vicar of Wakefield (1766), Laurence Sterne's Tristram Shandy (1759–67) and A Sentimental Journey (1768), Henry Brooke's The Fool of Quality (1765–70), Henry Mackenzie's The Man of Feeling (1771) and Maria Edgeworth's Castle Rackrent (1800).",
                "The physical landscape is prominent in the poetry of this period. The Romantics, and especially Wordsworth, are often described as \"nature poets\". However, these \"nature poems\" reveal wider concerns in that they are often meditations on \"an emotional problem or personal crisis\".[18]\n" +
                        "\n" +
                        "The poet, painter and printmaker William Blake (1757–1827) was an early writer of his kind. Largely disconnected from the major streams of the literature of his time, Blake was generally unrecognized during his lifetime but is now considered a seminal figure in the history of both the poetry and visual arts of the Romantic Age. Considered mad by contemporaries for his idiosyncratic views, Blake is held in high regard by later critics for his expressiveness and creativity, and for the philosophical and mystical undercurrents within his work. Among his most important works are Songs of Innocence (1789) and Songs of Experience (1794), \"and profound and difficult 'prophecies'\" such as Visions of the Daughters of Albion (1793), The Book of Urizen (1794), Milton (1804–1810) and Jerusalem The Emanation of the Giant Albion (1804–1820).\n" +
                        "\n" +
                        "After Blake, among the earliest Romantics were the Lake Poets, a small group of friends, including William Wordsworth (1770–1850), Samuel Taylor Coleridge (1772–1834), Robert Southey (1774–1843) and journalist Thomas De Quincey (1785–1859). However, at the time, Walter Scott (1771–1832) was the most famous poet. Scott achieved immediate success with his long narrative poem The Lay of the Last Minstrel in 1805, followed by the full epic poem Marmion in 1808. Both were set in the distant Scottish past. The early Romantic poets brought a new form of emotionalism and introspection, and their emergence is marked by the first romantic manifesto in English literature, the Preface to Lyrical Ballads (1798). In it Wordsworth discusses what he sees as the elements of a new type of poetry, one based on the \"real language of men\", and which avoids the poetic diction of much 18th-century poetry. Here, Wordsworth gives his famous definition of poetry, as \"the spontaneous overflow of powerful feelings\" which \"takes its origin from emotion recollected in tranquility\". The poems in Lyrical Ballads were mostly by Wordsworth, though Coleridge contributed one of the great poems of English literature, the long Rime of the Ancient Mariner, a tragic ballad about the survival of one sailor through a series of supernatural events on his voyage through the South Seas, and involves the symbolically significant slaying of an albatross. Coleridge is also especially remembered for Kubla Khan, Frost at Midnight, Dejection: An Ode, Christabel, as well as the major prose work, Biographia Literaria. His critical work, especially on Shakespeare, was highly influential, and he helped introduce German idealist philosophy to English-speaking culture. Coleridge and Wordsworth, along with Carlyle, were major influences through Emerson, on American transcendentalism. Among Wordsworth's most important poems are Michael, Lines Written a Few Miles Above Tintern Abbey , Resolution and Independence, Ode: Intimations of Immortality and the long, autobiographical epic The Prelude. The Prelude was begun in 1799, but published posthumously in 1850. Wordsworth's poetry is noteworthy for how he \"inverted the traditional hierarchy of poetic genres, subjects, and style by elevating humble and rustic life and the plain into the main subject and medium of poetry in general\", and how, in Coleridge's words, he awakens in the reader a \"freshness of sensation\" in his depiction of familiar, commonplace objects.\n" +
                        "\n" +
                        "Robert Southey (1774–1843) was another of the so-called \"Lake Poets\", and Poet Laureate for 30 years from 1813 to his death in 1843, although his fame has been long eclipsed by that of his contemporaries and friends William Wordsworth and Samuel Taylor Coleridge. Thomas De Quincey (1785–1859) was an English essayist, best known for his Confessions of an English Opium-Eater (1821), an autobiographical account of his laudanum use and its effect on his life. William Hazlitt (1778–1830), friend of both Coleridge and Wordsworth, is another important essayist at this time, though today he is best known for his literary criticism, especially Characters of Shakespear's Plays (1817–18).")
        );
        topics.add(new Model(R.drawable.ma_10,
                R.drawable.m_10,
                "Mavzu 11",
                " Mark Twain – a founder of a humorous story genre in American literature.",
                "Samuel Langhorne Clemens (November 30, 1835 – April 21, 1910), known by his pen name Mark Twain, was an American writer, humorist, entrepreneur, publisher, and lecturer. He was lauded as the \"greatest humorist the United States has produced,\" and William Faulkner called him \"the father of American literature\". His novels include The Adventures of Tom Sawyer (1876) and its sequel, Adventures of Huckleberry Finn (1884), the latter of which has often been called the \"Great American Novel\".\n" +
                        "\n" +
                        "Twain was raised in Hannibal, Missouri, which later provided the setting for Tom Sawyer and Huckleberry Finn. He served an apprenticeship with a printer and then worked as a typesetter, contributing articles to the newspaper of his older brother Orion Clemens. He later became a riverboat pilot on the Mississippi River before heading west to join Orion in Nevada. He referred humorously to his lack of success at mining, turning to journalism for the Virginia City Territorial Enterprise. His humorous story \"The Celebrated Jumping Frog of Calaveras County\" was published in 1865, based on a story that he heard at Angels Hotel in Angels Camp, California, where he had spent some time as a miner. The short story brought international attention and was even translated into French. His wit and satire, in prose and in speech, earned praise from critics and peers, and he was a friend to presidents, artists, industrialists, and European royalty.\n" +
                        "\n" +
                        "Twain earned a great deal of money from his writings and lectures but invested in ventures that lost most of it—such as the Paige Compositor, a mechanical typesetter that failed because of its complexity and imprecision. He filed for bankruptcy in the wake of these financial setbacks, but in time overcame his financial troubles with the help of Henry Huttleston Rogers. He eventually paid all his creditors in full, even though his bankruptcy relieved him of having to do so. Twain was born shortly after an appearance of Halley's Comet, and he predicted that he would \"go out with it\" as well; he died the day after the comet made its closest approach to the Earth.",
                "Twain began his career writing light, humorous verse, but he became a chronicler of the vanities, hypocrisies, and murderous acts of mankind. At mid-career, he combined rich humor, sturdy narrative, and social criticism in Huckleberry Finn. He was a master of rendering colloquial speech and helped to create and popularize a distinctive American literature built on American themes and language.\n" +
                        "\n" +
                        "Many of his works have been suppressed at times for various reasons. The Adventures of Huckleberry Finn has been repeatedly restricted in American high schools, not least for its frequent use of the word \"nigger\", which was in common usage in the pre-Civil War period in which the novel was set.\n" +
                        "\n" +
                        "A complete bibliography of Twain's works is nearly impossible to compile because of the vast number of pieces he wrote (often in obscure newspapers) and his use of several different pen names. Additionally, a large portion of his speeches and lectures have been lost or were not recorded; thus, the compilation of Twain's works is an ongoing process. Researchers rediscovered published material as recently as 1995 and 2015.\n" +
                        "Twain was writing for the Virginia City newspaper the Territorial Enterprise in 1863 when he met lawyer Tom Fitch, editor of the competing newspaper Virginia Daily Union and known as the \"silver-tongued orator of the Pacific\". He credited Fitch with giving him his \"first really profitable lesson\" in writing. \"When I first began to lecture, and in my earlier writings,\" Twain later commented, \"my sole idea was to make comic capital out of everything I saw and heard.\" In 1866, he presented his lecture on the Sandwich Islands to a crowd in Washoe City, Nevada.[81] Afterwards, Fitch told him:\n" +
                        "\n" +
                        "Clemens, your lecture was magnificent. It was eloquent, moving, sincere. Never in my entire life have I listened to such a magnificent piece of descriptive narration. But you committed one unpardonable sin – the unpardonable sin. It is a sin you must never commit again. You closed a most eloquent description, by which you had keyed your audience up to a pitch of the intensest interest, with a piece of atrocious anti-climax which nullified all the really fine effect you had produced.")
        );


        return topics;
    }

}
